/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1alpha1 "github.com/istio-ecosystem/admiral/admiral/pkg/apis/admiral/v1alpha1"
	admiralv1alpha1 "github.com/istio-ecosystem/admiral/admiral/pkg/client/applyconfiguration/admiral/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClientConnectionConfigs implements ClientConnectionConfigInterface
type FakeClientConnectionConfigs struct {
	Fake *FakeAdmiralV1alpha1
	ns   string
}

var clientconnectionconfigsResource = v1alpha1.SchemeGroupVersion.WithResource("clientconnectionconfigs")

var clientconnectionconfigsKind = v1alpha1.SchemeGroupVersion.WithKind("ClientConnectionConfig")

// Get takes name of the clientConnectionConfig, and returns the corresponding clientConnectionConfig object, and an error if there is any.
func (c *FakeClientConnectionConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClientConnectionConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(clientconnectionconfigsResource, c.ns, name), &v1alpha1.ClientConnectionConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClientConnectionConfig), err
}

// List takes label and field selectors, and returns the list of ClientConnectionConfigs that match those selectors.
func (c *FakeClientConnectionConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClientConnectionConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(clientconnectionconfigsResource, clientconnectionconfigsKind, c.ns, opts), &v1alpha1.ClientConnectionConfigList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ClientConnectionConfigList{ListMeta: obj.(*v1alpha1.ClientConnectionConfigList).ListMeta}
	for _, item := range obj.(*v1alpha1.ClientConnectionConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clientConnectionConfigs.
func (c *FakeClientConnectionConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(clientconnectionconfigsResource, c.ns, opts))

}

// Create takes the representation of a clientConnectionConfig and creates it.  Returns the server's representation of the clientConnectionConfig, and an error, if there is any.
func (c *FakeClientConnectionConfigs) Create(ctx context.Context, clientConnectionConfig *v1alpha1.ClientConnectionConfig, opts v1.CreateOptions) (result *v1alpha1.ClientConnectionConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(clientconnectionconfigsResource, c.ns, clientConnectionConfig), &v1alpha1.ClientConnectionConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClientConnectionConfig), err
}

// Update takes the representation of a clientConnectionConfig and updates it. Returns the server's representation of the clientConnectionConfig, and an error, if there is any.
func (c *FakeClientConnectionConfigs) Update(ctx context.Context, clientConnectionConfig *v1alpha1.ClientConnectionConfig, opts v1.UpdateOptions) (result *v1alpha1.ClientConnectionConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(clientconnectionconfigsResource, c.ns, clientConnectionConfig), &v1alpha1.ClientConnectionConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClientConnectionConfig), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeClientConnectionConfigs) UpdateStatus(ctx context.Context, clientConnectionConfig *v1alpha1.ClientConnectionConfig, opts v1.UpdateOptions) (*v1alpha1.ClientConnectionConfig, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(clientconnectionconfigsResource, "status", c.ns, clientConnectionConfig), &v1alpha1.ClientConnectionConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClientConnectionConfig), err
}

// Delete takes name of the clientConnectionConfig and deletes it. Returns an error if one occurs.
func (c *FakeClientConnectionConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(clientconnectionconfigsResource, c.ns, name, opts), &v1alpha1.ClientConnectionConfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClientConnectionConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(clientconnectionconfigsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ClientConnectionConfigList{})
	return err
}

// Patch applies the patch and returns the patched clientConnectionConfig.
func (c *FakeClientConnectionConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClientConnectionConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(clientconnectionconfigsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ClientConnectionConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClientConnectionConfig), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied clientConnectionConfig.
func (c *FakeClientConnectionConfigs) Apply(ctx context.Context, clientConnectionConfig *admiralv1alpha1.ClientConnectionConfigApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.ClientConnectionConfig, err error) {
	if clientConnectionConfig == nil {
		return nil, fmt.Errorf("clientConnectionConfig provided to Apply must not be nil")
	}
	data, err := json.Marshal(clientConnectionConfig)
	if err != nil {
		return nil, err
	}
	name := clientConnectionConfig.Name
	if name == nil {
		return nil, fmt.Errorf("clientConnectionConfig.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(clientconnectionconfigsResource, c.ns, *name, types.ApplyPatchType, data), &v1alpha1.ClientConnectionConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClientConnectionConfig), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeClientConnectionConfigs) ApplyStatus(ctx context.Context, clientConnectionConfig *admiralv1alpha1.ClientConnectionConfigApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.ClientConnectionConfig, err error) {
	if clientConnectionConfig == nil {
		return nil, fmt.Errorf("clientConnectionConfig provided to Apply must not be nil")
	}
	data, err := json.Marshal(clientConnectionConfig)
	if err != nil {
		return nil, err
	}
	name := clientConnectionConfig.Name
	if name == nil {
		return nil, fmt.Errorf("clientConnectionConfig.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(clientconnectionconfigsResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1alpha1.ClientConnectionConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClientConnectionConfig), err
}
