apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: greeting-canary
  labels:
    identity: greeting.canary
spec:
  replicas: 2
  selector:
    matchLabels:
      app: greeting
  template:
    metadata:
      annotations:
        admiral.io/env: stage
        sidecar.istio.io/inject: "true"
      labels:
        app: greeting
        identity: greeting.canary
    spec:
      containers:
        - image: nginx
          imagePullPolicy: IfNotPresent
          name: greeting
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx
              name: nginx-conf
              readOnly: true
            - mountPath: /var/log/nginx
              name: log
          resources:
            requests:
              cpu: "10m"
              memory: "50Mi"
            limits:
              cpu: "20m"
              memory: "75Mi"
      volumes:
        - configMap:
            items:
              - key: nginx.conf
                path: nginx.conf
            name: nginx-conf
          name: nginx-conf
        - emptyDir: {}
          name: log
  strategy:
    canary: # A new field that used to provide configurable options for a Canary strategy
      canaryService: rollout-canary-svc  # required
      stableService: rollout-stable-svc  # required
      trafficRouting:
        istio:
          virtualService:
            name: rollout-vsvc   # required
            routes:
              - primary
      steps:
      - setWeight: 10
      - pause:
          duration: 300 #300 seconds
---
kind: Service
apiVersion: v1
metadata:
  name: rollout-stable-svc
  labels:
    app: greeting
    identity: greeting.canary
  namespace: sample
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: greeting
---
kind: Service
apiVersion: v1
metadata:
  name: rollout-canary-svc
  labels:
    app: greeting
    identity: greeting.canary
  namespace: sample
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: greeting

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rollout-vsvc
spec:
  gateways:
  - mesh
  hosts:
  - istio-rollout.dev.argoproj.io
  http:
    - name: primary        # referenced in canary.trafficRouting.istio.virtualService.routes
      route:
      - destination:
          host: rollout-stable-svc # referenced in canary.stableService
        weight: 100
      - destination:
          host: rollout-canary-svc # referenced in canary.canaryService
        weight: 0