apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: greeting
spec:
  replicas: 2
  selector:
    matchLabels:
      app: greeting
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: greeting
        identity: greeting
    spec:
      containers:
        - image: nginx
          name: greeting
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx
              name: nginx-conf
              readOnly: true
            - mountPath: /var/log/nginx
              name: log
      volumes:
        - configMap:
            items:
              - key: nginx.conf
                path: nginx.conf
            name: nginx-conf
          name: nginx-conf
        - emptyDir: {}
          name: log
  strategy:
    # ----- Everything above this comment are the same as a deployment -----
    canary: # A new field that used to provide configurable options for a Canary strategy
      steps:
        - setWeight: 50
        - pause: {}
---
kind: Service
apiVersion: v1
metadata:
  name: rollout-canary
  labels:
    app: greeting
    identity: greeting
  namespace: sample
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: greeting