/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1alpha1 "github.com/istio-ecosystem/admiral/admiral/pkg/apis/admiral/v1alpha1"
	admiralv1alpha1 "github.com/istio-ecosystem/admiral/admiral/pkg/client/applyconfiguration/admiral/v1alpha1"
	scheme "github.com/istio-ecosystem/admiral/admiral/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DependenciesGetter has a method to return a DependencyInterface.
// A group's client should implement this interface.
type DependenciesGetter interface {
	Dependencies(namespace string) DependencyInterface
}

// DependencyInterface has methods to work with Dependency resources.
type DependencyInterface interface {
	Create(ctx context.Context, dependency *v1alpha1.Dependency, opts v1.CreateOptions) (*v1alpha1.Dependency, error)
	Update(ctx context.Context, dependency *v1alpha1.Dependency, opts v1.UpdateOptions) (*v1alpha1.Dependency, error)
	UpdateStatus(ctx context.Context, dependency *v1alpha1.Dependency, opts v1.UpdateOptions) (*v1alpha1.Dependency, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Dependency, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.DependencyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Dependency, err error)
	Apply(ctx context.Context, dependency *admiralv1alpha1.DependencyApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Dependency, err error)
	ApplyStatus(ctx context.Context, dependency *admiralv1alpha1.DependencyApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Dependency, err error)
	DependencyExpansion
}

// dependencies implements DependencyInterface
type dependencies struct {
	client rest.Interface
	ns     string
}

// newDependencies returns a Dependencies
func newDependencies(c *AdmiralV1alpha1Client, namespace string) *dependencies {
	return &dependencies{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the dependency, and returns the corresponding dependency object, and an error if there is any.
func (c *dependencies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Dependency, err error) {
	result = &v1alpha1.Dependency{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("dependencies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Dependencies that match those selectors.
func (c *dependencies) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DependencyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.DependencyList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("dependencies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested dependencies.
func (c *dependencies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("dependencies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a dependency and creates it.  Returns the server's representation of the dependency, and an error, if there is any.
func (c *dependencies) Create(ctx context.Context, dependency *v1alpha1.Dependency, opts v1.CreateOptions) (result *v1alpha1.Dependency, err error) {
	result = &v1alpha1.Dependency{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("dependencies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dependency).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a dependency and updates it. Returns the server's representation of the dependency, and an error, if there is any.
func (c *dependencies) Update(ctx context.Context, dependency *v1alpha1.Dependency, opts v1.UpdateOptions) (result *v1alpha1.Dependency, err error) {
	result = &v1alpha1.Dependency{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("dependencies").
		Name(dependency.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dependency).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *dependencies) UpdateStatus(ctx context.Context, dependency *v1alpha1.Dependency, opts v1.UpdateOptions) (result *v1alpha1.Dependency, err error) {
	result = &v1alpha1.Dependency{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("dependencies").
		Name(dependency.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dependency).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the dependency and deletes it. Returns an error if one occurs.
func (c *dependencies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("dependencies").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *dependencies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("dependencies").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched dependency.
func (c *dependencies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Dependency, err error) {
	result = &v1alpha1.Dependency{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("dependencies").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied dependency.
func (c *dependencies) Apply(ctx context.Context, dependency *admiralv1alpha1.DependencyApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Dependency, err error) {
	if dependency == nil {
		return nil, fmt.Errorf("dependency provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(dependency)
	if err != nil {
		return nil, err
	}
	name := dependency.Name
	if name == nil {
		return nil, fmt.Errorf("dependency.Name must be provided to Apply")
	}
	result = &v1alpha1.Dependency{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("dependencies").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *dependencies) ApplyStatus(ctx context.Context, dependency *admiralv1alpha1.DependencyApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Dependency, err error) {
	if dependency == nil {
		return nil, fmt.Errorf("dependency provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(dependency)
	if err != nil {
		return nil, err
	}

	name := dependency.Name
	if name == nil {
		return nil, fmt.Errorf("dependency.Name must be provided to Apply")
	}

	result = &v1alpha1.Dependency{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("dependencies").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
