/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1alpha1 "github.com/istio-ecosystem/admiral/admiral/pkg/apis/admiral/v1alpha1"
	admiralv1alpha1 "github.com/istio-ecosystem/admiral/admiral/pkg/client/applyconfiguration/admiral/v1alpha1"
	scheme "github.com/istio-ecosystem/admiral/admiral/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// OutlierDetectionsGetter has a method to return a OutlierDetectionInterface.
// A group's client should implement this interface.
type OutlierDetectionsGetter interface {
	OutlierDetections(namespace string) OutlierDetectionInterface
}

// OutlierDetectionInterface has methods to work with OutlierDetection resources.
type OutlierDetectionInterface interface {
	Create(ctx context.Context, outlierDetection *v1alpha1.OutlierDetection, opts v1.CreateOptions) (*v1alpha1.OutlierDetection, error)
	Update(ctx context.Context, outlierDetection *v1alpha1.OutlierDetection, opts v1.UpdateOptions) (*v1alpha1.OutlierDetection, error)
	UpdateStatus(ctx context.Context, outlierDetection *v1alpha1.OutlierDetection, opts v1.UpdateOptions) (*v1alpha1.OutlierDetection, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.OutlierDetection, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.OutlierDetectionList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.OutlierDetection, err error)
	Apply(ctx context.Context, outlierDetection *admiralv1alpha1.OutlierDetectionApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.OutlierDetection, err error)
	ApplyStatus(ctx context.Context, outlierDetection *admiralv1alpha1.OutlierDetectionApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.OutlierDetection, err error)
	OutlierDetectionExpansion
}

// outlierDetections implements OutlierDetectionInterface
type outlierDetections struct {
	client rest.Interface
	ns     string
}

// newOutlierDetections returns a OutlierDetections
func newOutlierDetections(c *AdmiralV1alpha1Client, namespace string) *outlierDetections {
	return &outlierDetections{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the outlierDetection, and returns the corresponding outlierDetection object, and an error if there is any.
func (c *outlierDetections) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.OutlierDetection, err error) {
	result = &v1alpha1.OutlierDetection{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("outlierdetections").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of OutlierDetections that match those selectors.
func (c *outlierDetections) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.OutlierDetectionList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.OutlierDetectionList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("outlierdetections").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested outlierDetections.
func (c *outlierDetections) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("outlierdetections").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a outlierDetection and creates it.  Returns the server's representation of the outlierDetection, and an error, if there is any.
func (c *outlierDetections) Create(ctx context.Context, outlierDetection *v1alpha1.OutlierDetection, opts v1.CreateOptions) (result *v1alpha1.OutlierDetection, err error) {
	result = &v1alpha1.OutlierDetection{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("outlierdetections").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(outlierDetection).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a outlierDetection and updates it. Returns the server's representation of the outlierDetection, and an error, if there is any.
func (c *outlierDetections) Update(ctx context.Context, outlierDetection *v1alpha1.OutlierDetection, opts v1.UpdateOptions) (result *v1alpha1.OutlierDetection, err error) {
	result = &v1alpha1.OutlierDetection{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("outlierdetections").
		Name(outlierDetection.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(outlierDetection).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *outlierDetections) UpdateStatus(ctx context.Context, outlierDetection *v1alpha1.OutlierDetection, opts v1.UpdateOptions) (result *v1alpha1.OutlierDetection, err error) {
	result = &v1alpha1.OutlierDetection{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("outlierdetections").
		Name(outlierDetection.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(outlierDetection).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the outlierDetection and deletes it. Returns an error if one occurs.
func (c *outlierDetections) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("outlierdetections").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *outlierDetections) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("outlierdetections").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched outlierDetection.
func (c *outlierDetections) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.OutlierDetection, err error) {
	result = &v1alpha1.OutlierDetection{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("outlierdetections").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied outlierDetection.
func (c *outlierDetections) Apply(ctx context.Context, outlierDetection *admiralv1alpha1.OutlierDetectionApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.OutlierDetection, err error) {
	if outlierDetection == nil {
		return nil, fmt.Errorf("outlierDetection provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(outlierDetection)
	if err != nil {
		return nil, err
	}
	name := outlierDetection.Name
	if name == nil {
		return nil, fmt.Errorf("outlierDetection.Name must be provided to Apply")
	}
	result = &v1alpha1.OutlierDetection{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("outlierdetections").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *outlierDetections) ApplyStatus(ctx context.Context, outlierDetection *admiralv1alpha1.OutlierDetectionApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.OutlierDetection, err error) {
	if outlierDetection == nil {
		return nil, fmt.Errorf("outlierDetection provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(outlierDetection)
	if err != nil {
		return nil, err
	}

	name := outlierDetection.Name
	if name == nil {
		return nil, fmt.Errorf("outlierDetection.Name must be provided to Apply")
	}

	result = &v1alpha1.OutlierDetection{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("outlierdetections").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
