/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1alpha1 "github.com/istio-ecosystem/admiral/admiral/pkg/apis/admiral/v1alpha1"
	admiralv1alpha1 "github.com/istio-ecosystem/admiral/admiral/pkg/client/applyconfiguration/admiral/v1alpha1"
	scheme "github.com/istio-ecosystem/admiral/admiral/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// TrafficConfigsGetter has a method to return a TrafficConfigInterface.
// A group's client should implement this interface.
type TrafficConfigsGetter interface {
	TrafficConfigs(namespace string) TrafficConfigInterface
}

// TrafficConfigInterface has methods to work with TrafficConfig resources.
type TrafficConfigInterface interface {
	Create(ctx context.Context, trafficConfig *v1alpha1.TrafficConfig, opts v1.CreateOptions) (*v1alpha1.TrafficConfig, error)
	Update(ctx context.Context, trafficConfig *v1alpha1.TrafficConfig, opts v1.UpdateOptions) (*v1alpha1.TrafficConfig, error)
	UpdateStatus(ctx context.Context, trafficConfig *v1alpha1.TrafficConfig, opts v1.UpdateOptions) (*v1alpha1.TrafficConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.TrafficConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.TrafficConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.TrafficConfig, err error)
	Apply(ctx context.Context, trafficConfig *admiralv1alpha1.TrafficConfigApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.TrafficConfig, err error)
	ApplyStatus(ctx context.Context, trafficConfig *admiralv1alpha1.TrafficConfigApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.TrafficConfig, err error)
	TrafficConfigExpansion
}

// trafficConfigs implements TrafficConfigInterface
type trafficConfigs struct {
	client rest.Interface
	ns     string
}

// newTrafficConfigs returns a TrafficConfigs
func newTrafficConfigs(c *AdmiralV1alpha1Client, namespace string) *trafficConfigs {
	return &trafficConfigs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the trafficConfig, and returns the corresponding trafficConfig object, and an error if there is any.
func (c *trafficConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.TrafficConfig, err error) {
	result = &v1alpha1.TrafficConfig{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("trafficconfigs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of TrafficConfigs that match those selectors.
func (c *trafficConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.TrafficConfigList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.TrafficConfigList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("trafficconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested trafficConfigs.
func (c *trafficConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("trafficconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a trafficConfig and creates it.  Returns the server's representation of the trafficConfig, and an error, if there is any.
func (c *trafficConfigs) Create(ctx context.Context, trafficConfig *v1alpha1.TrafficConfig, opts v1.CreateOptions) (result *v1alpha1.TrafficConfig, err error) {
	result = &v1alpha1.TrafficConfig{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("trafficconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(trafficConfig).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a trafficConfig and updates it. Returns the server's representation of the trafficConfig, and an error, if there is any.
func (c *trafficConfigs) Update(ctx context.Context, trafficConfig *v1alpha1.TrafficConfig, opts v1.UpdateOptions) (result *v1alpha1.TrafficConfig, err error) {
	result = &v1alpha1.TrafficConfig{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("trafficconfigs").
		Name(trafficConfig.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(trafficConfig).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *trafficConfigs) UpdateStatus(ctx context.Context, trafficConfig *v1alpha1.TrafficConfig, opts v1.UpdateOptions) (result *v1alpha1.TrafficConfig, err error) {
	result = &v1alpha1.TrafficConfig{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("trafficconfigs").
		Name(trafficConfig.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(trafficConfig).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the trafficConfig and deletes it. Returns an error if one occurs.
func (c *trafficConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("trafficconfigs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *trafficConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("trafficconfigs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched trafficConfig.
func (c *trafficConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.TrafficConfig, err error) {
	result = &v1alpha1.TrafficConfig{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("trafficconfigs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied trafficConfig.
func (c *trafficConfigs) Apply(ctx context.Context, trafficConfig *admiralv1alpha1.TrafficConfigApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.TrafficConfig, err error) {
	if trafficConfig == nil {
		return nil, fmt.Errorf("trafficConfig provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(trafficConfig)
	if err != nil {
		return nil, err
	}
	name := trafficConfig.Name
	if name == nil {
		return nil, fmt.Errorf("trafficConfig.Name must be provided to Apply")
	}
	result = &v1alpha1.TrafficConfig{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("trafficconfigs").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *trafficConfigs) ApplyStatus(ctx context.Context, trafficConfig *admiralv1alpha1.TrafficConfigApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.TrafficConfig, err error) {
	if trafficConfig == nil {
		return nil, fmt.Errorf("trafficConfig provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(trafficConfig)
	if err != nil {
		return nil, err
	}

	name := trafficConfig.Name
	if name == nil {
		return nil, fmt.Errorf("trafficConfig.Name must be provided to Apply")
	}

	result = &v1alpha1.TrafficConfig{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("trafficconfigs").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
