[[constraint]]
  name = "istio.io/api"
  branch ="release-1.1"

[[constraint]]
  name = "istio.io/istio"
  branch ="release-1.1"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.2.0"

[[constraint]]
  name = "k8s.io/api"
  branch ="release-1.11"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.11"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  branch = "release-1.11"

[[constraint]]
  name = "k8s.io/kubernetes"
  branch = "release-1.11"

[[constraint]]
   name = "k8s.io/gengo"
   branch = "master"

[[constraint]]
  name = "k8s.io/client-go"
  branch = "release-8.0"


[[constraint]]
  name = "k8s.io/helm"
  version = "2.9.1"

[prune]
  go-tests = true
  unused-packages = true