apiVersion: numaflow.numaproj.io/v1alpha1
kind: MonoVertex
metadata:
  name: simple-mono-vertex
spec:
  metadata:
    annotations:
      sidecar.istio.io/inject: "true"
    labels:
      identity: monovertex
  source:
    udsource:
      container:
        image: quay.io/numaio/numaflow-java/source-simple-source:stable
    # transformer is an optional container to do any transformation to the incoming data before passing to the sink
    transformer:
      container:
        image: quay.io/numaio/numaflow-rs/source-transformer-now:stable
  sink:
    udsink:
      container:
        image: quay.io/numaio/numaflow-java/simple-sink:stable