---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admiral-secret-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admiral-secret-role
subjects:
  - kind: ServiceAccount
    name: admiral
    namespace: admiral

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admiral-dependency-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admiral-dependency-role
subjects:
  - kind: ServiceAccount
    name: admiral
    namespace: admiral

---
