

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: admiral-dependency-role
rules:
  - apiGroups: ["intuit.com"]
    resources: ["dependencies"]
    verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: admiral-secret-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]