

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: admiral-dependency-role
  namespace: admiral
rules:
  - apiGroups: ["admiral.io"]
    resources: ["dependencies"]
    verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: admiral-secret-role
  namespace: admiral
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: admiral-configmap-role
  namespace: admiral-sync
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "update", "create"]

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admiral-sync-write-envoyfilters
  namespace: admiral
rules:
  - apiGroups: ["networking.istio.io"]
    resources: ['envoyfilters']
    verbs: ["create", "update", "delete", "patch"]