apiVersion: v1
kind: Service
metadata:
  name: admiral-http
spec:
  type: NodePort
  selector:
    app: admiral
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32000
---
apiVersion: v1
kind: Service
metadata:
  name: admiral-metrics
spec:
  type: NodePort
  selector:
    app: admiral
  ports:
    - protocol: TCP
      port: 6900
      targetPort: 6900
      nodePort: 32001