apiVersion: admiral.io/v1alpha1
kind: GlobalTrafficPolicy
metadata:
  name: gtp-service1
  namespace: sample
  annotations:
    admiral.io/env: stage
  labels:
    identity: greeting
    priority: "1" #0 value or missing label represents no priority is set, any other value determines the processing priority
spec:
  policy:
    - dnsPrefix: default # default is a keyword, alternatively you can use `env` (ex: stage)
      lbType: 1 #0 represents TOPOLOGY, 1 represents FAILOVER
      target:
        - region: us-west-2
          weight: 80
        - region: us-east-2
          weight: 20
