apiVersion: admiral.io/v1alpha1
kind: GlobalTrafficPolicy
metadata:
  name: gtp-service1
  namespace: sample
  labels:
    identity: greeting
spec:
  policy:
    - dns: default.greeting.global
      lbtype: FAILOVER
      target:
        - region: uswest-2
          weight: 100
        - region: useast-2
          weight: 0
