apiVersion: admiral.io/v1alpha1
kind: GlobalTrafficPolicy
metadata:
  name: gtp-service1
  namespace: sample
  labels:
    identity: greeting
spec:
  policy:
    - dns: default
      lbType: 0
    - dns: west
      lbType: 1 #0 represents TOPOLOGY, 1 represents FAILOVER
      target:
        - region: us-west-2
          weight: 100
        - region: us-east-2
          weight: 0
    - dns: east
      lbType: 1 #0 represents TOPOLOGY, 1 represents FAILOVER
      target:
        - region: us-west-2
          weight: 0
        - region: us-east-2
          weight: 100
