---
apiVersion: admiral.io/v1
kind: Dependency
metadata:
  name: dependency
  namespace: admiral
spec:
  source: webapp
  #TODO this value is hard coded to identity
  identityLabel: identity
  destinations:
    - greeting
---

---
apiVersion: admiral.io/v1
kind: Dependency
metadata:
  name: dependency-grpc-client
  namespace: admiral
spec:
  source: grpc-client
  identityLabel: identity
  destinations:
    - grpc-server
---