apiVersion: admiral.io/v1alpha1
kind: RoutingPolicy
metadata:
  name: greeting-routing-policy
  annotations:
    admiral.io/env: stage
  labels:
    identity: greeting
spec:
  plugin: greeting
  hosts:
    - qal.greeting.mesh
  config:
    cachePrefix: cache-v1
    cachettlSec: "86400"
    dispatcherUrl: qal.greeting.dispatcher.mesh
    algo: greetingDispatcher
    pathPrefix: "/wpcatalog,/consumercatalog,/v1/company/{id}/auth/hydrate,/consumercatalog"

