/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/istio-ecosystem/admiral/admiral/pkg/apis/admiral/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// TrafficConfigLister helps list TrafficConfigs.
// All objects returned here must be treated as read-only.
type TrafficConfigLister interface {
	// List lists all TrafficConfigs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.TrafficConfig, err error)
	// TrafficConfigs returns an object that can list and get TrafficConfigs.
	TrafficConfigs(namespace string) TrafficConfigNamespaceLister
	TrafficConfigListerExpansion
}

// trafficConfigLister implements the TrafficConfigLister interface.
type trafficConfigLister struct {
	indexer cache.Indexer
}

// NewTrafficConfigLister returns a new TrafficConfigLister.
func NewTrafficConfigLister(indexer cache.Indexer) TrafficConfigLister {
	return &trafficConfigLister{indexer: indexer}
}

// List lists all TrafficConfigs in the indexer.
func (s *trafficConfigLister) List(selector labels.Selector) (ret []*v1alpha1.TrafficConfig, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.TrafficConfig))
	})
	return ret, err
}

// TrafficConfigs returns an object that can list and get TrafficConfigs.
func (s *trafficConfigLister) TrafficConfigs(namespace string) TrafficConfigNamespaceLister {
	return trafficConfigNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// TrafficConfigNamespaceLister helps list and get TrafficConfigs.
// All objects returned here must be treated as read-only.
type TrafficConfigNamespaceLister interface {
	// List lists all TrafficConfigs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.TrafficConfig, err error)
	// Get retrieves the TrafficConfig from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.TrafficConfig, error)
	TrafficConfigNamespaceListerExpansion
}

// trafficConfigNamespaceLister implements the TrafficConfigNamespaceLister
// interface.
type trafficConfigNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all TrafficConfigs in the indexer for a given namespace.
func (s trafficConfigNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.TrafficConfig, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.TrafficConfig))
	})
	return ret, err
}

// Get retrieves the TrafficConfig from the indexer for a given namespace and name.
func (s trafficConfigNamespaceLister) Get(name string) (*v1alpha1.TrafficConfig, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("trafficconfig"), name)
	}
	return obj.(*v1alpha1.TrafficConfig), nil
}
