/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

// DependencyListerExpansion allows custom methods to be added to
// DependencyLister.
type DependencyListerExpansion interface{}

// DependencyNamespaceListerExpansion allows custom methods to be added to
// DependencyNamespaceLister.
type DependencyNamespaceListerExpansion interface{}

// GlobalTrafficPolicyListerExpansion allows custom methods to be added to
// GlobalTrafficPolicyLister.
type GlobalTrafficPolicyListerExpansion interface{}

// GlobalTrafficPolicyNamespaceListerExpansion allows custom methods to be added to
// GlobalTrafficPolicyNamespaceLister.
type GlobalTrafficPolicyNamespaceListerExpansion interface{}

// RoutingPolicyListerExpansion allows custom methods to be added to
// RoutingPolicyLister.
type RoutingPolicyListerExpansion interface{}

// RoutingPolicyNamespaceListerExpansion allows custom methods to be added to
// RoutingPolicyNamespaceLister.
type RoutingPolicyNamespaceListerExpansion interface{}
