/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/istio-ecosystem/admiral/admiral/pkg/apis/admiral/v1alpha1"
)

// AppOverrideApplyConfiguration represents an declarative configuration of the AppOverride type for use
// with apply.
type AppOverrideApplyConfiguration struct {
	AssetAlias *string            `json:"assetAlias,omitempty"`
	AssetID    *string            `json:"assetID,omitempty"`
	Weights    []*v1alpha1.Weight `json:"weights,omitempty"`
}

// AppOverrideApplyConfiguration constructs an declarative configuration of the AppOverride type for use with
// apply.
func AppOverride() *AppOverrideApplyConfiguration {
	return &AppOverrideApplyConfiguration{}
}

// WithAssetAlias sets the AssetAlias field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AssetAlias field is set to the value of the last call.
func (b *AppOverrideApplyConfiguration) WithAssetAlias(value string) *AppOverrideApplyConfiguration {
	b.AssetAlias = &value
	return b
}

// WithAssetID sets the AssetID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AssetID field is set to the value of the last call.
func (b *AppOverrideApplyConfiguration) WithAssetID(value string) *AppOverrideApplyConfiguration {
	b.AssetID = &value
	return b
}

// WithWeights adds the given value to the Weights field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Weights field.
func (b *AppOverrideApplyConfiguration) WithWeights(values ...**v1alpha1.Weight) *AppOverrideApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithWeights")
		}
		b.Weights = append(b.Weights, *values[i])
	}
	return b
}
