/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/istio-ecosystem/admiral/admiral/pkg/apis/admiral/v1alpha1"
)

// AppQuotaGroupApplyConfiguration represents an declarative configuration of the AppQuotaGroup type for use
// with apply.
type AppQuotaGroupApplyConfiguration struct {
	Name                 *string           `json:"name,omitempty"`
	Description          *string           `json:"description,omitempty"`
	Quotas               []*v1alpha1.Quota `json:"quotas,omitempty"`
	AssociatedApps       []string          `json:"associatedApps,omitempty"`
	WorkloadEnvSelectors []string          `json:"workloadEnvSelectors,omitempty"`
}

// AppQuotaGroupApplyConfiguration constructs an declarative configuration of the AppQuotaGroup type for use with
// apply.
func AppQuotaGroup() *AppQuotaGroupApplyConfiguration {
	return &AppQuotaGroupApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *AppQuotaGroupApplyConfiguration) WithName(value string) *AppQuotaGroupApplyConfiguration {
	b.Name = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *AppQuotaGroupApplyConfiguration) WithDescription(value string) *AppQuotaGroupApplyConfiguration {
	b.Description = &value
	return b
}

// WithQuotas adds the given value to the Quotas field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Quotas field.
func (b *AppQuotaGroupApplyConfiguration) WithQuotas(values ...**v1alpha1.Quota) *AppQuotaGroupApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithQuotas")
		}
		b.Quotas = append(b.Quotas, *values[i])
	}
	return b
}

// WithAssociatedApps adds the given value to the AssociatedApps field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AssociatedApps field.
func (b *AppQuotaGroupApplyConfiguration) WithAssociatedApps(values ...string) *AppQuotaGroupApplyConfiguration {
	for i := range values {
		b.AssociatedApps = append(b.AssociatedApps, values[i])
	}
	return b
}

// WithWorkloadEnvSelectors adds the given value to the WorkloadEnvSelectors field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the WorkloadEnvSelectors field.
func (b *AppQuotaGroupApplyConfiguration) WithWorkloadEnvSelectors(values ...string) *AppQuotaGroupApplyConfiguration {
	for i := range values {
		b.WorkloadEnvSelectors = append(b.WorkloadEnvSelectors, values[i])
	}
	return b
}
