/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// HeaderApplyConfiguration represents an declarative configuration of the Header type for use
// with apply.
type HeaderApplyConfiguration struct {
	Name      *string `json:"name,omitempty"`
	Value     *string `json:"value,omitempty"`
	Condition *string `json:"condition,omitempty"`
}

// HeaderApplyConfiguration constructs an declarative configuration of the Header type for use with
// apply.
func Header() *HeaderApplyConfiguration {
	return &HeaderApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *HeaderApplyConfiguration) WithName(value string) *HeaderApplyConfiguration {
	b.Name = &value
	return b
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *HeaderApplyConfiguration) WithValue(value string) *HeaderApplyConfiguration {
	b.Value = &value
	return b
}

// WithCondition sets the Condition field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Condition field is set to the value of the last call.
func (b *HeaderApplyConfiguration) WithCondition(value string) *HeaderApplyConfiguration {
	b.Condition = &value
	return b
}
