/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/istio-ecosystem/admiral/admiral/pkg/apis/admiral/v1alpha1"
)

// QuotaGroupApplyConfiguration represents an declarative configuration of the QuotaGroup type for use
// with apply.
type QuotaGroupApplyConfiguration struct {
	TotalQuotaGroup []*v1alpha1.TotalQuotaGroup `json:"totalQuotaGroups,omitempty"`
	AppQuotaGroups  []*v1alpha1.AppQuotaGroup   `json:"appQuotaGroups,omitempty"`
}

// QuotaGroupApplyConfiguration constructs an declarative configuration of the QuotaGroup type for use with
// apply.
func QuotaGroup() *QuotaGroupApplyConfiguration {
	return &QuotaGroupApplyConfiguration{}
}

// WithTotalQuotaGroup adds the given value to the TotalQuotaGroup field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TotalQuotaGroup field.
func (b *QuotaGroupApplyConfiguration) WithTotalQuotaGroup(values ...**v1alpha1.TotalQuotaGroup) *QuotaGroupApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTotalQuotaGroup")
		}
		b.TotalQuotaGroup = append(b.TotalQuotaGroup, *values[i])
	}
	return b
}

// WithAppQuotaGroups adds the given value to the AppQuotaGroups field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AppQuotaGroups field.
func (b *QuotaGroupApplyConfiguration) WithAppQuotaGroups(values ...**v1alpha1.AppQuotaGroup) *QuotaGroupApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAppQuotaGroups")
		}
		b.AppQuotaGroups = append(b.AppQuotaGroups, *values[i])
	}
	return b
}
