/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/istio-ecosystem/admiral/admiral/pkg/apis/admiral/v1alpha1"
)

// TargetGroupApplyConfiguration represents an declarative configuration of the TargetGroup type for use
// with apply.
type TargetGroupApplyConfiguration struct {
	Name         *string                 `json:"name,omitempty"`
	Weights      []*v1alpha1.Weight      `json:"weights,omitempty"`
	AppOverrides []*v1alpha1.AppOverride `json:"appOverrides,omitempty"`
}

// TargetGroupApplyConfiguration constructs an declarative configuration of the TargetGroup type for use with
// apply.
func TargetGroup() *TargetGroupApplyConfiguration {
	return &TargetGroupApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *TargetGroupApplyConfiguration) WithName(value string) *TargetGroupApplyConfiguration {
	b.Name = &value
	return b
}

// WithWeights adds the given value to the Weights field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Weights field.
func (b *TargetGroupApplyConfiguration) WithWeights(values ...**v1alpha1.Weight) *TargetGroupApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithWeights")
		}
		b.Weights = append(b.Weights, *values[i])
	}
	return b
}

// WithAppOverrides adds the given value to the AppOverrides field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AppOverrides field.
func (b *TargetGroupApplyConfiguration) WithAppOverrides(values ...**v1alpha1.AppOverride) *TargetGroupApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAppOverrides")
		}
		b.AppOverrides = append(b.AppOverrides, *values[i])
	}
	return b
}
