/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// TrafficConfigSpecApplyConfiguration represents an declarative configuration of the TrafficConfigSpec type for use
// with apply.
type TrafficConfigSpecApplyConfiguration struct {
	WorkloadEnv []string                       `json:"workloadEnvs,omitempty"`
	EdgeService *EdgeServiceApplyConfiguration `json:"edgeService,omitempty"`
	QuotaGroup  *QuotaGroupApplyConfiguration  `json:"quotaGroup,omitempty"`
}

// TrafficConfigSpecApplyConfiguration constructs an declarative configuration of the TrafficConfigSpec type for use with
// apply.
func TrafficConfigSpec() *TrafficConfigSpecApplyConfiguration {
	return &TrafficConfigSpecApplyConfiguration{}
}

// WithWorkloadEnv adds the given value to the WorkloadEnv field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the WorkloadEnv field.
func (b *TrafficConfigSpecApplyConfiguration) WithWorkloadEnv(values ...string) *TrafficConfigSpecApplyConfiguration {
	for i := range values {
		b.WorkloadEnv = append(b.WorkloadEnv, values[i])
	}
	return b
}

// WithEdgeService sets the EdgeService field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EdgeService field is set to the value of the last call.
func (b *TrafficConfigSpecApplyConfiguration) WithEdgeService(value *EdgeServiceApplyConfiguration) *TrafficConfigSpecApplyConfiguration {
	b.EdgeService = value
	return b
}

// WithQuotaGroup sets the QuotaGroup field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the QuotaGroup field is set to the value of the last call.
func (b *TrafficConfigSpecApplyConfiguration) WithQuotaGroup(value *QuotaGroupApplyConfiguration) *TrafficConfigSpecApplyConfiguration {
	b.QuotaGroup = value
	return b
}
