---
apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: server
    identity: Admiral.platform.mesh.server
    env: stage
spec:
  ports:
  - port: 80
    targetPort: 5000
    name: http
  selector:
    app: server
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: server-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: server
        identity: Admiral.platform.mesh.server
        version: v1
        env: stage
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: server
        image: istio/examples-helloworld-v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
---
