---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sleep
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sleep
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: sleep
        identity: sleep
        istio-injected: "true"
    spec:
      serviceAccountName: sleep
      containers:
        - name: sleep
          image: pstauffer/curl
          command: ["/bin/sleep", "3650d"]
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: sleep
  labels:
    app: sleep
    identity: sleep
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: sleep
---