---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  annotations:
    #admiral.io/ignore: "true" #Uncommenting this line will cause admiral to ignore this deployment despite the fact that it's in the mesh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      annotations:
        admiral.io/env: stage
        sidecar.istio.io/inject: "true"
      labels:
        app: webapp
        identity: webapp
        #admiral-ignore: "true" #Uncommenting this line will cause admiral to ignore this deployment despite the fact that it's in the mesh
    spec:
      serviceAccountName: webapp
      containers:
        - name: webapp
          image: pstauffer/curl
          command: ["/bin/sleep", "3650d"]
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "10m"
              memory: "50Mi"
            limits:
              cpu: "20m"
              memory: "75Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: webapp
    identity: webapp
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: webapp
---