apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dependencies.admiral.io
spec:
  group: admiral.io
  names:
    kind: Dependency
    plural: dependencies
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: generic cdr object to wrap the dependency api
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              properties:
                destinations:
                  description: 'REQUIRED: A list of workloads that source workload depends
                  on.'
                  items:
                    type: string
                  type: array
                identityLabel:
                  description: 'REQUIRED: the label on the workload for selecting source
                  and destination'
                  type: string
                source:
                  description: 'REQUIRED: identifier for the source workload'
                  type: string
              type: object
          required:
            - metadata
            - spec
          type: object
      served: true
      storage: true