apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: globaltrafficpolicies.admiral.io
spec:
  group: admiral.io
  version: v1alpha1
  names:
    kind: GlobalTrafficPolicy
    plural: globaltrafficpolicies
  scope: Namespaced