apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: routingpolicies.admiral.io
spec:
  group: admiral.io
  names:
    kind: RoutingPolicy
    listKind: RoutingPolicyList
    plural: routingpolicies
    shortNames:
      - rp
      - rps
    singular: routingpolicy
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          description: generic cdr object to wrap the GlobalTrafficPolicy api
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              properties:
                config:
                  additionalProperties:
                    type: string
                  type: object
                hosts:
                  items:
                    type: string
                  type: array
                plugin:
                  type: string
              type: object
            status:
              properties:
                clustersSynced:
                  format: int32
                  type: integer
                state:
                  type: string
              required:
                - clustersSynced
                - state
              type: object
          required:
            - metadata
            - spec
            - status
          type: object
      served: true
      storage: true
