// Code generated by protoc-gen-go. DO NOT EDIT.
// source: clientconnectionconfig.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConnectionPool_HTTP_H2UpgradePolicy int32

const (
	ConnectionPool_HTTP_DEFAULT        ConnectionPool_HTTP_H2UpgradePolicy = 0
	ConnectionPool_HTTP_DO_NOT_UPGRADE ConnectionPool_HTTP_H2UpgradePolicy = 1
	ConnectionPool_HTTP_UPGRADE        ConnectionPool_HTTP_H2UpgradePolicy = 2
)

var ConnectionPool_HTTP_H2UpgradePolicy_name = map[int32]string{
	0: "DEFAULT",
	1: "DO_NOT_UPGRADE",
	2: "UPGRADE",
}

var ConnectionPool_HTTP_H2UpgradePolicy_value = map[string]int32{
	"DEFAULT":        0,
	"DO_NOT_UPGRADE": 1,
	"UPGRADE":        2,
}

func (x ConnectionPool_HTTP_H2UpgradePolicy) String() string {
	return proto.EnumName(ConnectionPool_HTTP_H2UpgradePolicy_name, int32(x))
}

func (ConnectionPool_HTTP_H2UpgradePolicy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_282331a83280fd5c, []int{1, 2, 0}
}

type ClientConnectionConfig struct {
	ConnectionPool       *ConnectionPool `protobuf:"bytes,1,opt,name=connectionPool,proto3" json:"connectionPool,omitempty"`
	Tunnel               *Tunnel         `protobuf:"bytes,2,opt,name=tunnel,proto3" json:"tunnel,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ClientConnectionConfig) Reset()         { *m = ClientConnectionConfig{} }
func (m *ClientConnectionConfig) String() string { return proto.CompactTextString(m) }
func (*ClientConnectionConfig) ProtoMessage()    {}
func (*ClientConnectionConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_282331a83280fd5c, []int{0}
}

func (m *ClientConnectionConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientConnectionConfig.Unmarshal(m, b)
}
func (m *ClientConnectionConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientConnectionConfig.Marshal(b, m, deterministic)
}
func (m *ClientConnectionConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientConnectionConfig.Merge(m, src)
}
func (m *ClientConnectionConfig) XXX_Size() int {
	return xxx_messageInfo_ClientConnectionConfig.Size(m)
}
func (m *ClientConnectionConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientConnectionConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ClientConnectionConfig proto.InternalMessageInfo

func (m *ClientConnectionConfig) GetConnectionPool() *ConnectionPool {
	if m != nil {
		return m.ConnectionPool
	}
	return nil
}

func (m *ClientConnectionConfig) GetTunnel() *Tunnel {
	if m != nil {
		return m.Tunnel
	}
	return nil
}

type ConnectionPool struct {
	Tcp                  *ConnectionPool_TCP  `protobuf:"bytes,1,opt,name=tcp,proto3" json:"tcp,omitempty"`
	Http                 *ConnectionPool_HTTP `protobuf:"bytes,2,opt,name=http,proto3" json:"http,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ConnectionPool) Reset()         { *m = ConnectionPool{} }
func (m *ConnectionPool) String() string { return proto.CompactTextString(m) }
func (*ConnectionPool) ProtoMessage()    {}
func (*ConnectionPool) Descriptor() ([]byte, []int) {
	return fileDescriptor_282331a83280fd5c, []int{1}
}

func (m *ConnectionPool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionPool.Unmarshal(m, b)
}
func (m *ConnectionPool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionPool.Marshal(b, m, deterministic)
}
func (m *ConnectionPool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionPool.Merge(m, src)
}
func (m *ConnectionPool) XXX_Size() int {
	return xxx_messageInfo_ConnectionPool.Size(m)
}
func (m *ConnectionPool) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionPool.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionPool proto.InternalMessageInfo

func (m *ConnectionPool) GetTcp() *ConnectionPool_TCP {
	if m != nil {
		return m.Tcp
	}
	return nil
}

func (m *ConnectionPool) GetHttp() *ConnectionPool_HTTP {
	if m != nil {
		return m.Http
	}
	return nil
}

type ConnectionPool_TcpKeepalive struct {
	Probes               uint32   `protobuf:"varint,1,opt,name=probes,proto3" json:"probes,omitempty"`
	Time                 string   `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Interval             string   `protobuf:"bytes,3,opt,name=interval,proto3" json:"interval,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectionPool_TcpKeepalive) Reset()         { *m = ConnectionPool_TcpKeepalive{} }
func (m *ConnectionPool_TcpKeepalive) String() string { return proto.CompactTextString(m) }
func (*ConnectionPool_TcpKeepalive) ProtoMessage()    {}
func (*ConnectionPool_TcpKeepalive) Descriptor() ([]byte, []int) {
	return fileDescriptor_282331a83280fd5c, []int{1, 0}
}

func (m *ConnectionPool_TcpKeepalive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionPool_TcpKeepalive.Unmarshal(m, b)
}
func (m *ConnectionPool_TcpKeepalive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionPool_TcpKeepalive.Marshal(b, m, deterministic)
}
func (m *ConnectionPool_TcpKeepalive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionPool_TcpKeepalive.Merge(m, src)
}
func (m *ConnectionPool_TcpKeepalive) XXX_Size() int {
	return xxx_messageInfo_ConnectionPool_TcpKeepalive.Size(m)
}
func (m *ConnectionPool_TcpKeepalive) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionPool_TcpKeepalive.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionPool_TcpKeepalive proto.InternalMessageInfo

func (m *ConnectionPool_TcpKeepalive) GetProbes() uint32 {
	if m != nil {
		return m.Probes
	}
	return 0
}

func (m *ConnectionPool_TcpKeepalive) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *ConnectionPool_TcpKeepalive) GetInterval() string {
	if m != nil {
		return m.Interval
	}
	return ""
}

type ConnectionPool_TCP struct {
	// Maximum number of HTTP1 /TCP connections to a destination host.
	MaxConnections int32                        `protobuf:"varint,1,opt,name=maxConnections,proto3" json:"maxConnections,omitempty"`
	ConnectTimeout string                       `protobuf:"bytes,2,opt,name=connectTimeout,proto3" json:"connectTimeout,omitempty"`
	TcpKeepalive   *ConnectionPool_TcpKeepalive `protobuf:"bytes,3,opt,name=tcpKeepalive,proto3" json:"tcpKeepalive,omitempty"`
	// The maximum duration of a connection
	MaxConnectionDuration string   `protobuf:"bytes,4,opt,name=maxConnectionDuration,proto3" json:"maxConnectionDuration,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *ConnectionPool_TCP) Reset()         { *m = ConnectionPool_TCP{} }
func (m *ConnectionPool_TCP) String() string { return proto.CompactTextString(m) }
func (*ConnectionPool_TCP) ProtoMessage()    {}
func (*ConnectionPool_TCP) Descriptor() ([]byte, []int) {
	return fileDescriptor_282331a83280fd5c, []int{1, 1}
}

func (m *ConnectionPool_TCP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionPool_TCP.Unmarshal(m, b)
}
func (m *ConnectionPool_TCP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionPool_TCP.Marshal(b, m, deterministic)
}
func (m *ConnectionPool_TCP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionPool_TCP.Merge(m, src)
}
func (m *ConnectionPool_TCP) XXX_Size() int {
	return xxx_messageInfo_ConnectionPool_TCP.Size(m)
}
func (m *ConnectionPool_TCP) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionPool_TCP.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionPool_TCP proto.InternalMessageInfo

func (m *ConnectionPool_TCP) GetMaxConnections() int32 {
	if m != nil {
		return m.MaxConnections
	}
	return 0
}

func (m *ConnectionPool_TCP) GetConnectTimeout() string {
	if m != nil {
		return m.ConnectTimeout
	}
	return ""
}

func (m *ConnectionPool_TCP) GetTcpKeepalive() *ConnectionPool_TcpKeepalive {
	if m != nil {
		return m.TcpKeepalive
	}
	return nil
}

func (m *ConnectionPool_TCP) GetMaxConnectionDuration() string {
	if m != nil {
		return m.MaxConnectionDuration
	}
	return ""
}

// HTTP connection pool settings
type ConnectionPool_HTTP struct {
	// Maximum number of pending HTTP requests to a destination.
	Http1MaxPendingRequests int32 `protobuf:"varint,1,opt,name=http1MaxPendingRequests,proto3" json:"http1MaxPendingRequests,omitempty"`
	// Maximum number of requests to a backend
	Http2MaxRequests int32 `protobuf:"varint,2,opt,name=http2MaxRequests,proto3" json:"http2MaxRequests,omitempty"`
	// Maximum number of requests per connection to a backend.
	MaxRequestsPerConnection int32                               `protobuf:"varint,3,opt,name=maxRequestsPerConnection,proto3" json:"maxRequestsPerConnection,omitempty"`
	MaxRetries               int32                               `protobuf:"varint,4,opt,name=maxRetries,proto3" json:"maxRetries,omitempty"`
	IdleTimeout              string                              `protobuf:"bytes,5,opt,name=idleTimeout,proto3" json:"idleTimeout,omitempty"`
	H2UpgradePolicy          ConnectionPool_HTTP_H2UpgradePolicy `protobuf:"varint,6,opt,name=h2UpgradePolicy,proto3,enum=admiral.global.v1alpha.ConnectionPool_HTTP_H2UpgradePolicy" json:"h2UpgradePolicy,omitempty"`
	UseClientProtocol        bool                                `protobuf:"varint,7,opt,name=useClientProtocol,proto3" json:"useClientProtocol,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                            `json:"-"`
	XXX_unrecognized         []byte                              `json:"-"`
	XXX_sizecache            int32                               `json:"-"`
}

func (m *ConnectionPool_HTTP) Reset()         { *m = ConnectionPool_HTTP{} }
func (m *ConnectionPool_HTTP) String() string { return proto.CompactTextString(m) }
func (*ConnectionPool_HTTP) ProtoMessage()    {}
func (*ConnectionPool_HTTP) Descriptor() ([]byte, []int) {
	return fileDescriptor_282331a83280fd5c, []int{1, 2}
}

func (m *ConnectionPool_HTTP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionPool_HTTP.Unmarshal(m, b)
}
func (m *ConnectionPool_HTTP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionPool_HTTP.Marshal(b, m, deterministic)
}
func (m *ConnectionPool_HTTP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionPool_HTTP.Merge(m, src)
}
func (m *ConnectionPool_HTTP) XXX_Size() int {
	return xxx_messageInfo_ConnectionPool_HTTP.Size(m)
}
func (m *ConnectionPool_HTTP) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionPool_HTTP.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionPool_HTTP proto.InternalMessageInfo

func (m *ConnectionPool_HTTP) GetHttp1MaxPendingRequests() int32 {
	if m != nil {
		return m.Http1MaxPendingRequests
	}
	return 0
}

func (m *ConnectionPool_HTTP) GetHttp2MaxRequests() int32 {
	if m != nil {
		return m.Http2MaxRequests
	}
	return 0
}

func (m *ConnectionPool_HTTP) GetMaxRequestsPerConnection() int32 {
	if m != nil {
		return m.MaxRequestsPerConnection
	}
	return 0
}

func (m *ConnectionPool_HTTP) GetMaxRetries() int32 {
	if m != nil {
		return m.MaxRetries
	}
	return 0
}

func (m *ConnectionPool_HTTP) GetIdleTimeout() string {
	if m != nil {
		return m.IdleTimeout
	}
	return ""
}

func (m *ConnectionPool_HTTP) GetH2UpgradePolicy() ConnectionPool_HTTP_H2UpgradePolicy {
	if m != nil {
		return m.H2UpgradePolicy
	}
	return ConnectionPool_HTTP_DEFAULT
}

func (m *ConnectionPool_HTTP) GetUseClientProtocol() bool {
	if m != nil {
		return m.UseClientProtocol
	}
	return false
}

type Tunnel struct {
	Protocol             string   `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	TargetHost           string   `protobuf:"bytes,2,opt,name=targetHost,proto3" json:"targetHost,omitempty"`
	TargetPort           uint32   `protobuf:"varint,3,opt,name=targetPort,proto3" json:"targetPort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tunnel) Reset()         { *m = Tunnel{} }
func (m *Tunnel) String() string { return proto.CompactTextString(m) }
func (*Tunnel) ProtoMessage()    {}
func (*Tunnel) Descriptor() ([]byte, []int) {
	return fileDescriptor_282331a83280fd5c, []int{2}
}

func (m *Tunnel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tunnel.Unmarshal(m, b)
}
func (m *Tunnel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tunnel.Marshal(b, m, deterministic)
}
func (m *Tunnel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tunnel.Merge(m, src)
}
func (m *Tunnel) XXX_Size() int {
	return xxx_messageInfo_Tunnel.Size(m)
}
func (m *Tunnel) XXX_DiscardUnknown() {
	xxx_messageInfo_Tunnel.DiscardUnknown(m)
}

var xxx_messageInfo_Tunnel proto.InternalMessageInfo

func (m *Tunnel) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *Tunnel) GetTargetHost() string {
	if m != nil {
		return m.TargetHost
	}
	return ""
}

func (m *Tunnel) GetTargetPort() uint32 {
	if m != nil {
		return m.TargetPort
	}
	return 0
}

func init() {
	proto.RegisterEnum("admiral.global.v1alpha.ConnectionPool_HTTP_H2UpgradePolicy", ConnectionPool_HTTP_H2UpgradePolicy_name, ConnectionPool_HTTP_H2UpgradePolicy_value)
	proto.RegisterType((*ClientConnectionConfig)(nil), "admiral.global.v1alpha.ClientConnectionConfig")
	proto.RegisterType((*ConnectionPool)(nil), "admiral.global.v1alpha.ConnectionPool")
	proto.RegisterType((*ConnectionPool_TcpKeepalive)(nil), "admiral.global.v1alpha.ConnectionPool.TcpKeepalive")
	proto.RegisterType((*ConnectionPool_TCP)(nil), "admiral.global.v1alpha.ConnectionPool.TCP")
	proto.RegisterType((*ConnectionPool_HTTP)(nil), "admiral.global.v1alpha.ConnectionPool.HTTP")
	proto.RegisterType((*Tunnel)(nil), "admiral.global.v1alpha.Tunnel")
}

func init() { proto.RegisterFile("clientconnectionconfig.proto", fileDescriptor_282331a83280fd5c) }

var fileDescriptor_282331a83280fd5c = []byte{
	// 562 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xef, 0x6a, 0x13, 0x4f,
	0x14, 0xfd, 0x6d, 0xf3, 0xaf, 0xbf, 0x9b, 0x36, 0x8d, 0x17, 0x8c, 0x4b, 0x90, 0x12, 0xf2, 0xa1,
	0x84, 0x2a, 0x0b, 0x4d, 0x45, 0x44, 0x85, 0x52, 0x37, 0xd5, 0x80, 0xb6, 0x5d, 0x86, 0x8d, 0x82,
	0x5f, 0xca, 0x64, 0x77, 0x4c, 0x06, 0x66, 0x77, 0xd6, 0xcd, 0x24, 0xc4, 0xc7, 0xf0, 0x0d, 0x7c,
	0x14, 0x1f, 0xc6, 0x07, 0x91, 0x9d, 0xec, 0x26, 0x9b, 0xb4, 0x81, 0xf8, 0x29, 0xb9, 0xe7, 0xde,
	0x73, 0xee, 0x99, 0xb3, 0x33, 0xf0, 0xd4, 0x13, 0x9c, 0x85, 0xca, 0x93, 0x61, 0xc8, 0x3c, 0xc5,
	0x65, 0xe8, 0xc9, 0xf0, 0x1b, 0x1f, 0x59, 0x51, 0x2c, 0x95, 0xc4, 0x06, 0xf5, 0x03, 0x1e, 0x53,
	0x61, 0x8d, 0x84, 0x1c, 0x52, 0x61, 0xcd, 0xce, 0xa8, 0x88, 0xc6, 0xb4, 0xfd, 0xcb, 0x80, 0x86,
	0xad, 0x89, 0xf6, 0x92, 0x68, 0x6b, 0x22, 0xde, 0x40, 0x6d, 0x25, 0xe6, 0x48, 0x29, 0x4c, 0xa3,
	0x65, 0x74, 0xaa, 0xdd, 0x13, 0xeb, 0x61, 0x2d, 0xcb, 0x5e, 0x9b, 0x26, 0x1b, 0x6c, 0x7c, 0x09,
	0x65, 0x35, 0x0d, 0x43, 0x26, 0xcc, 0x3d, 0xad, 0x73, 0xbc, 0x4d, 0xc7, 0xd5, 0x53, 0x24, 0x9d,
	0x6e, 0xff, 0xac, 0x40, 0x6d, 0x5d, 0x1a, 0xdf, 0x42, 0x41, 0x79, 0x51, 0xea, 0xe7, 0x74, 0x37,
	0x3f, 0x96, 0x6b, 0x3b, 0x24, 0xa1, 0xe1, 0x05, 0x14, 0xc7, 0x4a, 0x45, 0xa9, 0x8d, 0x67, 0x3b,
	0xd2, 0xfb, 0xae, 0xeb, 0x10, 0x4d, 0x6c, 0x7e, 0x86, 0x03, 0xd7, 0x8b, 0x3e, 0x32, 0x16, 0x51,
	0xc1, 0x67, 0x0c, 0x1b, 0x50, 0x8e, 0x62, 0x39, 0x64, 0x13, 0xed, 0xe8, 0x90, 0xa4, 0x15, 0x22,
	0x14, 0x15, 0x0f, 0x98, 0x5e, 0xf4, 0x3f, 0xd1, 0xff, 0xb1, 0x09, 0xfb, 0x3c, 0x54, 0x2c, 0x9e,
	0x51, 0x61, 0x16, 0x34, 0xbe, 0xac, 0x9b, 0x7f, 0x0c, 0x28, 0xb8, 0xb6, 0x83, 0x27, 0x50, 0x0b,
	0xe8, 0x7c, 0xb5, 0x7f, 0xa1, 0x5b, 0x22, 0x1b, 0x68, 0x32, 0x97, 0x66, 0xec, 0xf2, 0x80, 0xc9,
	0xa9, 0x4a, 0x37, 0x6d, 0xa0, 0xf8, 0x05, 0x0e, 0x54, 0xce, 0xaf, 0xde, 0x5b, 0xed, 0x9e, 0xef,
	0x9a, 0x5b, 0x8e, 0x4a, 0xd6, 0x84, 0xf0, 0x05, 0x3c, 0x5e, 0xb3, 0xd4, 0x9b, 0xc6, 0x34, 0xf9,
	0x35, 0x8b, 0xda, 0xc7, 0xc3, 0xcd, 0xe6, 0xef, 0x02, 0x14, 0x93, 0x34, 0xf1, 0x15, 0x3c, 0x49,
	0xf2, 0x3c, 0xbb, 0xa6, 0x73, 0x87, 0x85, 0x3e, 0x0f, 0x47, 0x84, 0x7d, 0x9f, 0xb2, 0x89, 0xca,
	0x0e, 0xbc, 0xad, 0x8d, 0xa7, 0x50, 0x4f, 0x5a, 0xdd, 0x6b, 0x3a, 0x5f, 0x52, 0xf6, 0x34, 0xe5,
	0x1e, 0x8e, 0xaf, 0xc1, 0x0c, 0x56, 0xa5, 0xc3, 0xe2, 0x95, 0x25, 0x9d, 0x44, 0x89, 0x6c, 0xed,
	0xe3, 0x31, 0x80, 0xee, 0xa9, 0x98, 0xb3, 0x89, 0x3e, 0x55, 0x89, 0xe4, 0x10, 0x6c, 0x41, 0x95,
	0xfb, 0x82, 0x65, 0xf1, 0x97, 0xf4, 0xb1, 0xf3, 0x10, 0x32, 0x38, 0x1a, 0x77, 0x07, 0xd1, 0x28,
	0xa6, 0x3e, 0x73, 0xa4, 0xe0, 0xde, 0x0f, 0xb3, 0xdc, 0x32, 0x3a, 0xb5, 0xee, 0x9b, 0x7f, 0xb8,
	0x77, 0x56, 0x7f, 0x5d, 0x82, 0x6c, 0x6a, 0xe2, 0x73, 0x78, 0x34, 0x9d, 0xb0, 0xc5, 0x4b, 0x76,
	0x92, 0x17, 0xef, 0x49, 0x61, 0x56, 0x5a, 0x46, 0x67, 0x9f, 0xdc, 0x6f, 0xb4, 0x2f, 0xe0, 0x68,
	0x43, 0x11, 0xab, 0x50, 0xe9, 0x5d, 0xbd, 0xbf, 0x1c, 0x7c, 0x72, 0xeb, 0xff, 0x21, 0x42, 0xad,
	0x77, 0x7b, 0x77, 0x73, 0xeb, 0xde, 0x0d, 0x9c, 0x0f, 0xe4, 0xb2, 0x77, 0x55, 0x37, 0x92, 0x81,
	0xac, 0xd8, 0x6b, 0xfb, 0x50, 0x5e, 0xbc, 0xd2, 0xe4, 0x3e, 0x47, 0xd9, 0x3e, 0x63, 0x71, 0x9f,
	0xb3, 0x3a, 0x49, 0x4f, 0xd1, 0x78, 0xc4, 0x54, 0x5f, 0x4e, 0xb2, 0xbb, 0x99, 0x43, 0x56, 0x7d,
	0x47, 0xc6, 0x4a, 0x7f, 0x8b, 0x43, 0x92, 0x43, 0xde, 0x55, 0xbe, 0x96, 0x02, 0xe9, 0x33, 0x31,
	0x2c, 0x6b, 0xc9, 0xf3, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6c, 0xc5, 0x51, 0x76, 0xe4, 0x04,
	0x00, 0x00,
}
