// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dependencyproxy.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The below example of DependencyProxy
//```yaml
//    apiVersion: admiral.io/v1alpha1
//    kind: DependencyProxy
//    metadata:
//      name: dependency-proxy-example
//      namespace: admiral
//      annotations:
//          admiral.io/env: stage
//    spec:
//      destination:
//          identity: greeting
//          dns_suffix: "xyz"
//          dns_prefix:
//              - "test0"
//              - "test1"
//      proxy:
//          identity: nginx-gw
//```
// The above DependencyProxy will generate the following
// VirtualService object
//```yaml
//  apiVersion: networking.istio.io/v1alpha3
//  kind: VirtualService
//  metadata:
//      name: httpbin-vs
//  spec:
//      hosts:
//       - test0.stage.greeting.xyz
//       - test1.stage.greeting.xyz
//       - stage.greeting.xyz
//      http:
//       - route:
//          - destination:
//              host: stage.gateway.global
//              port:
//                number: 80
//```
//
type DependencyProxy struct {
	// Configuration of the destination identity for which the
	// requests should be proxied.
	Destination *Destination `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	// Configuration of the proxy's identity through which the requests
	// to the destination will be proxied through.
	Proxy                *Proxy   `protobuf:"bytes,2,opt,name=proxy,proto3" json:"proxy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DependencyProxy) Reset()         { *m = DependencyProxy{} }
func (m *DependencyProxy) String() string { return proto.CompactTextString(m) }
func (*DependencyProxy) ProtoMessage()    {}
func (*DependencyProxy) Descriptor() ([]byte, []int) {
	return fileDescriptor_edf7120455c08e23, []int{0}
}

func (m *DependencyProxy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DependencyProxy.Unmarshal(m, b)
}
func (m *DependencyProxy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DependencyProxy.Marshal(b, m, deterministic)
}
func (m *DependencyProxy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DependencyProxy.Merge(m, src)
}
func (m *DependencyProxy) XXX_Size() int {
	return xxx_messageInfo_DependencyProxy.Size(m)
}
func (m *DependencyProxy) XXX_DiscardUnknown() {
	xxx_messageInfo_DependencyProxy.DiscardUnknown(m)
}

var xxx_messageInfo_DependencyProxy proto.InternalMessageInfo

func (m *DependencyProxy) GetDestination() *Destination {
	if m != nil {
		return m.Destination
	}
	return nil
}

func (m *DependencyProxy) GetProxy() *Proxy {
	if m != nil {
		return m.Proxy
	}
	return nil
}

type Destination struct {
	// Identifier of the destination workload.
	Identity string `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	// An ordered list of all DNS prefixes.
	DnsPrefixes []string `protobuf:"bytes,2,rep,name=dns_prefixes,json=dnsPrefixes,proto3" json:"dns_prefixes,omitempty"`
	// The DNS suffix that should be appended while
	// constructing the endpoint of the destination service.
	DnsSuffix            string   `protobuf:"bytes,3,opt,name=dns_suffix,json=dnsSuffix,proto3" json:"dns_suffix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Destination) Reset()         { *m = Destination{} }
func (m *Destination) String() string { return proto.CompactTextString(m) }
func (*Destination) ProtoMessage()    {}
func (*Destination) Descriptor() ([]byte, []int) {
	return fileDescriptor_edf7120455c08e23, []int{1}
}

func (m *Destination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Destination.Unmarshal(m, b)
}
func (m *Destination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Destination.Marshal(b, m, deterministic)
}
func (m *Destination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Destination.Merge(m, src)
}
func (m *Destination) XXX_Size() int {
	return xxx_messageInfo_Destination.Size(m)
}
func (m *Destination) XXX_DiscardUnknown() {
	xxx_messageInfo_Destination.DiscardUnknown(m)
}

var xxx_messageInfo_Destination proto.InternalMessageInfo

func (m *Destination) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *Destination) GetDnsPrefixes() []string {
	if m != nil {
		return m.DnsPrefixes
	}
	return nil
}

func (m *Destination) GetDnsSuffix() string {
	if m != nil {
		return m.DnsSuffix
	}
	return ""
}

type Proxy struct {
	// Identifier of the proxy's workload
	Identity             string   `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Proxy) Reset()         { *m = Proxy{} }
func (m *Proxy) String() string { return proto.CompactTextString(m) }
func (*Proxy) ProtoMessage()    {}
func (*Proxy) Descriptor() ([]byte, []int) {
	return fileDescriptor_edf7120455c08e23, []int{2}
}

func (m *Proxy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proxy.Unmarshal(m, b)
}
func (m *Proxy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proxy.Marshal(b, m, deterministic)
}
func (m *Proxy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proxy.Merge(m, src)
}
func (m *Proxy) XXX_Size() int {
	return xxx_messageInfo_Proxy.Size(m)
}
func (m *Proxy) XXX_DiscardUnknown() {
	xxx_messageInfo_Proxy.DiscardUnknown(m)
}

var xxx_messageInfo_Proxy proto.InternalMessageInfo

func (m *Proxy) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func init() {
	proto.RegisterType((*DependencyProxy)(nil), "admiral.global.v1alpha1.DependencyProxy")
	proto.RegisterType((*Destination)(nil), "admiral.global.v1alpha1.Destination")
	proto.RegisterType((*Proxy)(nil), "admiral.global.v1alpha1.Proxy")
}

func init() { proto.RegisterFile("dependencyproxy.proto", fileDescriptor_edf7120455c08e23) }

var fileDescriptor_edf7120455c08e23 = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0xd9, 0x96, 0x55, 0x77, 0x56, 0x10, 0x02, 0xe2, 0x22, 0x28, 0x75, 0xf5, 0xd0, 0x53,
	0xa0, 0xea, 0x2f, 0x90, 0xe2, 0xb9, 0xc4, 0x9b, 0x17, 0x49, 0x9d, 0x59, 0x0d, 0xa6, 0x93, 0x90,
	0x44, 0xd9, 0xfd, 0x15, 0xfe, 0x65, 0x69, 0x2a, 0xb5, 0x97, 0x7a, 0xcc, 0xe3, 0xbd, 0xef, 0xbd,
	0x0c, 0x9c, 0x22, 0x79, 0x62, 0x24, 0x7e, 0x1d, 0x7c, 0x70, 0xfd, 0x20, 0x7d, 0x70, 0xc9, 0x89,
	0x33, 0x8d, 0x2b, 0x13, 0xb4, 0x95, 0x6f, 0xd6, 0x2d, 0xb5, 0x95, 0x5f, 0x33, 0x6d, 0xfd, 0xbb,
	0x9e, 0xb5, 0xdf, 0x05, 0x9c, 0xcc, 0xb7, 0x91, 0xc5, 0x3a, 0x22, 0x1e, 0xa1, 0x46, 0x8a, 0xc9,
	0xb0, 0x4e, 0xc6, 0x71, 0x53, 0x4c, 0x8a, 0x69, 0x7d, 0x7b, 0x23, 0xf7, 0x20, 0xe4, 0xfc, 0xcf,
	0xab, 0x76, 0x83, 0xe2, 0x1e, 0xca, 0xbc, 0xa1, 0x19, 0x65, 0xc2, 0xe5, 0x5e, 0x42, 0xae, 0x55,
	0x1b, 0x73, 0xfb, 0x01, 0xf5, 0x0e, 0x51, 0x9c, 0xc3, 0x91, 0x41, 0xe2, 0x64, 0xd2, 0x90, 0x97,
	0x54, 0x6a, 0xfb, 0x16, 0x57, 0x70, 0x8c, 0x1c, 0x5f, 0x7c, 0xa0, 0xce, 0xf4, 0x14, 0x9b, 0xd1,
	0x64, 0x3c, 0xad, 0x54, 0x8d, 0x1c, 0x17, 0xbf, 0x92, 0xb8, 0x00, 0x58, 0x5b, 0xe2, 0x67, 0xd7,
	0x99, 0xbe, 0x19, 0x67, 0x40, 0x85, 0x1c, 0x9f, 0xb2, 0xd0, 0x5e, 0x43, 0xb9, 0xf9, 0xf3, 0x3f,
	0x35, 0x0f, 0x87, 0xcf, 0xe5, 0xca, 0x21, 0xd9, 0xe5, 0x41, 0x3e, 0xe6, 0xdd, 0x4f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x43, 0x65, 0xf6, 0xba, 0x65, 0x01, 0x00, 0x00,
}
