// Code generated by protoc-gen-go. DO NOT EDIT.
// source: routingpolicy.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RoutingPolicy struct {
	Plugin               string        `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`
	Hosts                []string      `protobuf:"bytes,2,rep,name=hosts,proto3" json:"hosts,omitempty"`
	Config               *PolicyConfig `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RoutingPolicy) Reset()         { *m = RoutingPolicy{} }
func (m *RoutingPolicy) String() string { return proto.CompactTextString(m) }
func (*RoutingPolicy) ProtoMessage()    {}
func (*RoutingPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4d39db6b36beca3, []int{0}
}

func (m *RoutingPolicy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoutingPolicy.Unmarshal(m, b)
}
func (m *RoutingPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoutingPolicy.Marshal(b, m, deterministic)
}
func (m *RoutingPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoutingPolicy.Merge(m, src)
}
func (m *RoutingPolicy) XXX_Size() int {
	return xxx_messageInfo_RoutingPolicy.Size(m)
}
func (m *RoutingPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_RoutingPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_RoutingPolicy proto.InternalMessageInfo

func (m *RoutingPolicy) GetPlugin() string {
	if m != nil {
		return m.Plugin
	}
	return ""
}

func (m *RoutingPolicy) GetHosts() []string {
	if m != nil {
		return m.Hosts
	}
	return nil
}

func (m *RoutingPolicy) GetConfig() *PolicyConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type PolicyConfig struct {
	Cache                *CacheConfig `protobuf:"bytes,1,opt,name=cache,proto3" json:"cache,omitempty"`
	DirectorServiceUrl   string       `protobuf:"bytes,2,opt,name=directorServiceUrl,proto3" json:"directorServiceUrl,omitempty"`
	Algo                 string       `protobuf:"bytes,3,opt,name=algo,proto3" json:"algo,omitempty"`
	PathPrefix           []string     `protobuf:"bytes,4,rep,name=pathPrefix,proto3" json:"pathPrefix,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PolicyConfig) Reset()         { *m = PolicyConfig{} }
func (m *PolicyConfig) String() string { return proto.CompactTextString(m) }
func (*PolicyConfig) ProtoMessage()    {}
func (*PolicyConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4d39db6b36beca3, []int{1}
}

func (m *PolicyConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PolicyConfig.Unmarshal(m, b)
}
func (m *PolicyConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PolicyConfig.Marshal(b, m, deterministic)
}
func (m *PolicyConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PolicyConfig.Merge(m, src)
}
func (m *PolicyConfig) XXX_Size() int {
	return xxx_messageInfo_PolicyConfig.Size(m)
}
func (m *PolicyConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_PolicyConfig.DiscardUnknown(m)
}

var xxx_messageInfo_PolicyConfig proto.InternalMessageInfo

func (m *PolicyConfig) GetCache() *CacheConfig {
	if m != nil {
		return m.Cache
	}
	return nil
}

func (m *PolicyConfig) GetDirectorServiceUrl() string {
	if m != nil {
		return m.DirectorServiceUrl
	}
	return ""
}

func (m *PolicyConfig) GetAlgo() string {
	if m != nil {
		return m.Algo
	}
	return ""
}

func (m *PolicyConfig) GetPathPrefix() []string {
	if m != nil {
		return m.PathPrefix
	}
	return nil
}

type CacheConfig struct {
	Prefix               string   `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	TtlSec               int32    `protobuf:"varint,2,opt,name=ttlSec,proto3" json:"ttlSec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CacheConfig) Reset()         { *m = CacheConfig{} }
func (m *CacheConfig) String() string { return proto.CompactTextString(m) }
func (*CacheConfig) ProtoMessage()    {}
func (*CacheConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4d39db6b36beca3, []int{2}
}

func (m *CacheConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CacheConfig.Unmarshal(m, b)
}
func (m *CacheConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CacheConfig.Marshal(b, m, deterministic)
}
func (m *CacheConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CacheConfig.Merge(m, src)
}
func (m *CacheConfig) XXX_Size() int {
	return xxx_messageInfo_CacheConfig.Size(m)
}
func (m *CacheConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_CacheConfig.DiscardUnknown(m)
}

var xxx_messageInfo_CacheConfig proto.InternalMessageInfo

func (m *CacheConfig) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *CacheConfig) GetTtlSec() int32 {
	if m != nil {
		return m.TtlSec
	}
	return 0
}

func init() {
	proto.RegisterType((*RoutingPolicy)(nil), "admiral.global.v1alpha.RoutingPolicy")
	proto.RegisterType((*PolicyConfig)(nil), "admiral.global.v1alpha.PolicyConfig")
	proto.RegisterType((*CacheConfig)(nil), "admiral.global.v1alpha.CacheConfig")
}

func init() { proto.RegisterFile("routingpolicy.proto", fileDescriptor_e4d39db6b36beca3) }

var fileDescriptor_e4d39db6b36beca3 = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x95, 0xb6, 0x09, 0xca, 0x05, 0x16, 0x83, 0xaa, 0x4c, 0x28, 0x0a, 0x0c, 0x99, 0x2c,
	0x51, 0x26, 0x24, 0x58, 0xe8, 0x0b, 0x54, 0xae, 0x58, 0xd8, 0x5c, 0xc7, 0x4d, 0x2c, 0xb9, 0xb9,
	0xc8, 0x75, 0x2b, 0x10, 0xcf, 0xc4, 0x3b, 0xa2, 0x9e, 0x83, 0x94, 0xa1, 0xdd, 0xf2, 0xdf, 0x7d,
	0xf7, 0xff, 0xb9, 0x33, 0xdc, 0x3a, 0x3c, 0x78, 0xd3, 0x35, 0x3d, 0x5a, 0xa3, 0xbe, 0x79, 0xef,
	0xd0, 0x23, 0x9b, 0xcb, 0x7a, 0x67, 0x9c, 0xb4, 0xbc, 0xb1, 0xb8, 0x91, 0x96, 0x1f, 0x9f, 0xa4,
	0xed, 0x5b, 0x59, 0xfe, 0xc0, 0x8d, 0x08, 0xf8, 0x8a, 0x70, 0x36, 0x87, 0xa4, 0xb7, 0x87, 0xc6,
	0x74, 0x79, 0x54, 0x44, 0x55, 0x2a, 0x06, 0xc5, 0xee, 0x20, 0x6e, 0x71, 0xef, 0xf7, 0xf9, 0xa4,
	0x98, 0x56, 0xa9, 0x08, 0x82, 0xbd, 0x42, 0xa2, 0xb0, 0xdb, 0x9a, 0x26, 0x9f, 0x16, 0x51, 0x95,
	0x2d, 0x1e, 0xf9, 0xf9, 0x1c, 0x1e, 0xdc, 0x97, 0xc4, 0x8a, 0x61, 0xa6, 0xfc, 0x8d, 0xe0, 0x7a,
	0xdc, 0x60, 0x2f, 0x10, 0x2b, 0xa9, 0x5a, 0x4d, 0xd9, 0xd9, 0xe2, 0xe1, 0x92, 0xdb, 0xf2, 0x04,
	0x0d, 0x66, 0x61, 0x82, 0x71, 0x60, 0xb5, 0x71, 0x5a, 0x79, 0x74, 0x6b, 0xed, 0x8e, 0x46, 0xe9,
	0x0f, 0x67, 0xf3, 0x09, 0xed, 0x70, 0xa6, 0xc3, 0x18, 0xcc, 0xa4, 0x6d, 0x90, 0xfe, 0x3b, 0x15,
	0xf4, 0xcd, 0xee, 0x01, 0x7a, 0xe9, 0xdb, 0x95, 0xd3, 0x5b, 0xf3, 0x95, 0xcf, 0x68, 0xd1, 0x51,
	0xa5, 0x7c, 0x83, 0x6c, 0x94, 0x4c, 0xa7, 0x0a, 0xe8, 0xff, 0xa9, 0x48, 0x9d, 0xea, 0xde, 0xdb,
	0xb5, 0x56, 0x14, 0x1f, 0x8b, 0x41, 0xbd, 0x5f, 0x7d, 0xc6, 0x3b, 0xac, 0xb5, 0xdd, 0x24, 0xf4,
	0x26, 0xcf, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe1, 0xc3, 0x8a, 0x0e, 0xaa, 0x01, 0x00, 0x00,
}
