package clusters

import (
	"context"
	"sync"
	"testing"
	"time"

	argo "github.com/argoproj/argo-rollouts/pkg/apis/rollouts/v1alpha1"
	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	v1 "github.com/istio-ecosystem/admiral/admiral/pkg/apis/admiral/v1"
	admiralFake "github.com/istio-ecosystem/admiral/admiral/pkg/client/clientset/versioned/fake"
	"github.com/istio-ecosystem/admiral/admiral/pkg/controller/admiral"
	"github.com/istio-ecosystem/admiral/admiral/pkg/controller/common"
	v12 "k8s.io/api/apps/v1"
	v13 "k8s.io/api/core/v1"
	time2 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

var ignoreUnexported = cmpopts.IgnoreUnexported(v1.GlobalTrafficPolicy{}.Status)

func init() {
	p := common.AdmiralParams{
		KubeconfigPath:             "testdata/fake.config",
		LabelSet:                   &common.LabelSet{},
		EnableSAN:                  true,
		SANPrefix:                  "prefix",
		HostnameSuffix:             "mesh",
		SyncNamespace:              "ns",
		CacheRefreshDuration:       time.Minute,
		ClusterRegistriesNamespace: "default",
		DependenciesNamespace:      "default",
		SecretResolver:             "",
	}

	p.LabelSet.WorkloadIdentityKey = "identity"
	p.LabelSet.GlobalTrafficDeploymentLabel = "identity"

	common.InitializeConfig(p)
}

func TestDeploymentHandler(t *testing.T) {

	p := common.AdmiralParams{
		KubeconfigPath: "testdata/fake.config",
	}

	registry, _ := InitAdmiral(context.Background(), p)

	handler := DeploymentHandler{}

	gtpCache := &globalTrafficCache{}
	gtpCache.identityCache = make(map[string]*v1.GlobalTrafficPolicy)
	gtpCache.mutex = &sync.Mutex{}

	fakeCrdClient := admiralFake.NewSimpleClientset()

	gtpController := &admiral.GlobalTrafficController{CrdClient: fakeCrdClient}
	remoteController, _ := createMockRemoteController(func(i interface{}) {

	})
	remoteController.GlobalTraffic = gtpController

	registry.RemoteControllers = map[string]*RemoteController{"cluster-1": remoteController}

	registry.AdmiralCache.GlobalTrafficCache = gtpCache
	handler.RemoteRegistry = registry

	deployment := v12.Deployment{
		ObjectMeta: time2.ObjectMeta{
			Name:      "test",
			Namespace: "namespace",
			Labels:    map[string]string{"identity": "app1"},
		},
		Spec: v12.DeploymentSpec{
			Selector: &time2.LabelSelector{
				MatchLabels: map[string]string{"identity": "bar"},
			},
			Template: v13.PodTemplateSpec{
				ObjectMeta: time2.ObjectMeta{
					Labels: map[string]string{"identity": "bar", "istio-injected": "true", "env": "dev"},
				},
			},
		},
	}

	//Struct of test case info. Name is required.
	testCases := []struct {
		name                         string
		addedDeployment              *v12.Deployment
		expectedDeploymentCacheKey   string
		expectedIdentityCacheValue   *v1.GlobalTrafficPolicy
		expectedDeploymentCacheValue *v12.Deployment
	}{
		{
			name:                         "Shouldn't throw errors when called",
			addedDeployment:              &deployment,
			expectedDeploymentCacheKey:   "myGTP1",
			expectedIdentityCacheValue:   nil,
			expectedDeploymentCacheValue: nil,
		},
	}

	//Rather annoying, but wasn't able to get the autogenerated fake k8s client for GTP objects to allow me to list resources, so this test is only for not throwing errors. I'll be testing the rest of the fucntionality picemeal.
	//Side note, if anyone knows how to fix `level=error msg="Failed to list deployments in cluster, error: no kind \"GlobalTrafficPolicyList\" is registered for version \"admiral.io/v1\" in scheme \"pkg/runtime/scheme.go:101\""`, I'd love to hear it!
	//Already tried working through this: https://github.com/camilamacedo86/operator-sdk/blob/e40d7db97f0d132333b1e46ddf7b7f3cab1e379f/doc/user/unit-testing.md with no luck

	//Run the test for every provided case
	for _, c := range testCases {
		t.Run(c.name, func(t *testing.T) {
			gtpCache = &globalTrafficCache{}
			gtpCache.identityCache = make(map[string]*v1.GlobalTrafficPolicy)
			gtpCache.mutex = &sync.Mutex{}
			handler.RemoteRegistry.AdmiralCache.GlobalTrafficCache = gtpCache

			handler.Added(&deployment)
			handler.Deleted(&deployment)
		})
	}
}

func TestGlobalTrafficCache(t *testing.T) {
	deployment := v12.Deployment{}
	deployment.Namespace = "namespace"
	deployment.Name = "fake-app-deployment-qal"
	deployment.Spec = v12.DeploymentSpec{
		Template: v13.PodTemplateSpec{
			ObjectMeta: time2.ObjectMeta{
				Labels: map[string]string{"identity": "app1", "env": "e2e"},
			},
		},
	}
	deployment.Labels = map[string]string{"identity": "app1"}

	deploymentNoEnv := v12.Deployment{}
	deploymentNoEnv.Namespace = "namespace"
	deploymentNoEnv.Name = "fake-app-deployment-qal"
	deploymentNoEnv.Spec = v12.DeploymentSpec{
		Template: v13.PodTemplateSpec{
			ObjectMeta: time2.ObjectMeta{
				Labels: map[string]string{"identity": "app1"},
			},
		},
	}
	deploymentNoEnv.Labels = map[string]string{"identity": "app1"}

	e2eGtp := v1.GlobalTrafficPolicy{}
	e2eGtp.Labels = map[string]string{"identity": "app1", "env": "e2e"}
	e2eGtp.Namespace = "namespace"
	e2eGtp.Name = "myGTP"

	gtpCache := &globalTrafficCache{}
	gtpCache.identityCache = make(map[string]*v1.GlobalTrafficPolicy)
	gtpCache.mutex = &sync.Mutex{}

	//Struct of test case info. Name is required.
	testCases := []struct {
		name        string
		gtp         *v1.GlobalTrafficPolicy
		deployment  *v12.Deployment
		identity    string
		environment string
		gtpName     string
	}{
		{
			name:        "Base case",
			gtp:         &e2eGtp,
			deployment:  &deployment,
			identity:    "app1",
			environment: "e2e",
			gtpName:     "myGTP",
		},
		{
			name:        "No Deployment",
			gtp:         &e2eGtp,
			deployment:  nil,
			identity:    "app1",
			environment: "e2e",
			gtpName:     "myGTP",
		},
		{
			name:        "Handles lack of environment label properly",
			gtp:         &e2eGtp,
			deployment:  &deploymentNoEnv,
			identity:    "app1",
			environment: "default",
			gtpName:     "myGTP",
		},
	}

	//Run the test for every provided case
	for _, c := range testCases {
		t.Run(c.name, func(t *testing.T) {

			gtpCache.identityCache = make(map[string]*v1.GlobalTrafficPolicy)
			gtpCache.mutex = &sync.Mutex{}
			err := gtpCache.Put(c.gtp)
			if err != nil {
				t.Fatalf("Unexpected error: %v", err)
			}
			foundGtp := gtpCache.GetFromIdentity(c.identity, c.environment)
			if c.deployment != nil && !cmp.Equal(foundGtp, c.gtp, ignoreUnexported) {
				t.Fatalf("GTP Mismatch: %v", cmp.Diff(foundGtp, c.gtp, ignoreUnexported))
			}

			//no deployment means there should be nothing in the identity cache
			if c.deployment == nil && foundGtp != nil {
				t.Fatalf("GTP Mismatch: %v", cmp.Diff(foundGtp, nil, ignoreUnexported))
			}

			gtpCache.Delete(common.GetGtpIdentity(c.gtp), common.GetGtpEnv(c.gtp))
			if len(gtpCache.identityCache) != 0 {
				t.Fatalf("Identity cache not cleared properly on delete")
			}
		})
	}

}

//TODO fix test
func TestRolloutHandler(t *testing.T) {

	p := common.AdmiralParams{
		KubeconfigPath: "testdata/fake.config",
	}

	registry, _ := InitAdmiral(context.Background(), p)

	handler := RolloutHandler{}

	gtpCache := &globalTrafficCache{}
	gtpCache.identityCache = make(map[string]*v1.GlobalTrafficPolicy)
	gtpCache.mutex = &sync.Mutex{}

	fakeCrdClient := admiralFake.NewSimpleClientset()

	gtpController := &admiral.GlobalTrafficController{CrdClient: fakeCrdClient}
	remoteController, _ := createMockRemoteController(func(i interface{}) {

	})
	remoteController.GlobalTraffic = gtpController

	registry.RemoteControllers = map[string]*RemoteController{"cluster-1": remoteController}

	registry.AdmiralCache.GlobalTrafficCache = gtpCache
	handler.RemoteRegistry = registry

	rollout := argo.Rollout{
		ObjectMeta: time2.ObjectMeta{
			Name:      "test",
			Namespace: "namespace",
			Labels:    map[string]string{"identity": "app1"},
		},
		Spec: argo.RolloutSpec{
			Selector: &time2.LabelSelector{
				MatchLabels: map[string]string{"identity": "bar"},
			},
			Template: v13.PodTemplateSpec{
				ObjectMeta: time2.ObjectMeta{
					Labels: map[string]string{"identity": "bar", "istio-injected": "true", "env": "dev"},
				},
			},
		},
	}

	//Struct of test case info. Name is required.
	testCases := []struct {
		name                       string
		addedRolout                *argo.Rollout
		expectedRolloutCacheKey    string
		expectedIdentityCacheValue *v1.GlobalTrafficPolicy
		expectedRolloutCacheValue  *argo.Rollout
	}{{
		name:                       "Shouldn't throw errors when called",
		addedRolout:                &rollout,
		expectedRolloutCacheKey:    "myGTP1",
		expectedIdentityCacheValue: nil,
		expectedRolloutCacheValue:  nil,
	}, {
		name:                       "Shouldn't throw errors when called-no identity",
		addedRolout:                &argo.Rollout{},
		expectedRolloutCacheKey:    "myGTP1",
		expectedIdentityCacheValue: nil,
		expectedRolloutCacheValue:  nil,
	},
	}

	//Rather annoying, but wasn't able to get the autogenerated fake k8s client for GTP objects to allow me to list resources, so this test is only for not throwing errors. I'll be testing the rest of the fucntionality picemeal.
	//Side note, if anyone knows how to fix `level=error msg="Failed to list rollouts in cluster, error: no kind \"GlobalTrafficPolicyList\" is registered for version \"admiral.io/v1\" in scheme \"pkg/runtime/scheme.go:101\""`, I'd love to hear it!
	//Already tried working through this: https://github.com/camilamacedo86/operator-sdk/blob/e40d7db97f0d132333b1e46ddf7b7f3cab1e379f/doc/user/unit-testing.md with no luck

	//Run the test for every provided case
	for _, c := range testCases {
		t.Run(c.name, func(t *testing.T) {
			gtpCache = &globalTrafficCache{}
			gtpCache.identityCache = make(map[string]*v1.GlobalTrafficPolicy)
			gtpCache.mutex = &sync.Mutex{}
			handler.RemoteRegistry.AdmiralCache.GlobalTrafficCache = gtpCache

			handler.Added(c.addedRolout)
			handler.Deleted(c.addedRolout)
			handler.Updated(c.addedRolout)
		})
	}
}

func TestGlobalTrafficCacheForRollout(t *testing.T) {
	rollout := argo.Rollout{}
	rollout.Namespace = "namespace"
	rollout.Name = "fake-app-rollout-qal"
	rollout.Spec = argo.RolloutSpec{
		Template: v13.PodTemplateSpec{
			ObjectMeta: time2.ObjectMeta{
				Labels: map[string]string{"identity": "app1", "env": "e2e"},
			},
		},
	}
	rollout.Labels = map[string]string{"identity": "app1"}

	rolloutNoEnv := argo.Rollout{}
	rolloutNoEnv.Namespace = "namespace"
	rolloutNoEnv.Name = "fake-app-rollout-qal"
	rolloutNoEnv.Spec = argo.RolloutSpec{
		Template: v13.PodTemplateSpec{
			ObjectMeta: time2.ObjectMeta{
				Labels: map[string]string{"identity": "app1"},
			},
		},
	}
	rolloutNoEnv.Labels = map[string]string{"identity": "app1"}

	e2eGtp := v1.GlobalTrafficPolicy{}
	e2eGtp.Labels = map[string]string{"identity": "app1", "env": "e2e"}
	e2eGtp.Namespace = "namespace"
	e2eGtp.Name = "myGTP"

	gtpCache := &globalTrafficCache{}
	gtpCache.identityCache = make(map[string]*v1.GlobalTrafficPolicy)
	gtpCache.mutex = &sync.Mutex{}

	//Struct of test case info. Name is required.
	testCases := []struct {
		name        string
		gtp         *v1.GlobalTrafficPolicy
		rollout     *argo.Rollout
		identity    string
		environment string
		gtpName     string
	}{
		{
			name:        "Base case",
			gtp:         &e2eGtp,
			rollout:     &rollout,
			identity:    "app1",
			environment: "e2e",
			gtpName:     "myGTP",
		},
		{
			name:        "No rollout",
			gtp:         &e2eGtp,
			rollout:     nil,
			identity:    "app1",
			environment: "e2e",
			gtpName:     "myGTP",
		},
		{
			name:        "Handles lack of environment label properly",
			gtp:         &e2eGtp,
			rollout:     &rolloutNoEnv,
			identity:    "app1",
			environment: "default",
			gtpName:     "myGTP",
		},
	}

	//Run the test for every provided case
	for _, c := range testCases {
		t.Run(c.name, func(t *testing.T) {

			gtpCache.identityCache = make(map[string]*v1.GlobalTrafficPolicy)
			gtpCache.mutex = &sync.Mutex{}

			foundGtp := gtpCache.GetFromIdentity(c.identity, c.environment)
			if c.rollout != nil && !cmp.Equal(foundGtp, c.gtp, ignoreUnexported) {
				t.Fatalf("GTP Mismatch: %v", cmp.Diff(foundGtp, c.gtp, ignoreUnexported))
			}

			//no rollout means there should be nothing in the identity cache
			if c.rollout == nil && foundGtp != nil {
				t.Fatalf("GTP Mismatch: %v", cmp.Diff(foundGtp, nil, ignoreUnexported))
			}

			gtpCache.Delete(common.GetGtpIdentity(c.gtp), common.GetGtpEnv(c.gtp))
			if len(gtpCache.identityCache) != 0 {
				t.Fatalf("Identity cache not cleared properly on delete")
			}
		})
	}

}
