/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/admiral/admiral/pkg/apis/admiral/v1"
	scheme "github.com/admiral/admiral/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DependenciesGetter has a method to return a DependencyInterface.
// A group's client should implement this interface.
type DependenciesGetter interface {
	Dependencies(namespace string) DependencyInterface
}

// DependencyInterface has methods to work with Dependency resources.
type DependencyInterface interface {
	Create(*v1.Dependency) (*v1.Dependency, error)
	Update(*v1.Dependency) (*v1.Dependency, error)
	UpdateStatus(*v1.Dependency) (*v1.Dependency, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.Dependency, error)
	List(opts metav1.ListOptions) (*v1.DependencyList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Dependency, err error)
	DependencyExpansion
}

// dependencies implements DependencyInterface
type dependencies struct {
	client rest.Interface
	ns     string
}

// newDependencies returns a Dependencies
func newDependencies(c *AdmiralV1Client, namespace string) *dependencies {
	return &dependencies{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the dependency, and returns the corresponding dependency object, and an error if there is any.
func (c *dependencies) Get(name string, options metav1.GetOptions) (result *v1.Dependency, err error) {
	result = &v1.Dependency{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("dependencies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Dependencies that match those selectors.
func (c *dependencies) List(opts metav1.ListOptions) (result *v1.DependencyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.DependencyList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("dependencies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested dependencies.
func (c *dependencies) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("dependencies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a dependency and creates it.  Returns the server's representation of the dependency, and an error, if there is any.
func (c *dependencies) Create(dependency *v1.Dependency) (result *v1.Dependency, err error) {
	result = &v1.Dependency{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("dependencies").
		Body(dependency).
		Do().
		Into(result)
	return
}

// Update takes the representation of a dependency and updates it. Returns the server's representation of the dependency, and an error, if there is any.
func (c *dependencies) Update(dependency *v1.Dependency) (result *v1.Dependency, err error) {
	result = &v1.Dependency{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("dependencies").
		Name(dependency.Name).
		Body(dependency).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *dependencies) UpdateStatus(dependency *v1.Dependency) (result *v1.Dependency, err error) {
	result = &v1.Dependency{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("dependencies").
		Name(dependency.Name).
		SubResource("status").
		Body(dependency).
		Do().
		Into(result)
	return
}

// Delete takes name of the dependency and deletes it. Returns an error if one occurs.
func (c *dependencies) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("dependencies").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *dependencies) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("dependencies").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched dependency.
func (c *dependencies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Dependency, err error) {
	result = &v1.Dependency{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("dependencies").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
