/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/admiral/admiral/pkg/apis/admiral/v1"
	scheme "github.com/admiral/admiral/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// GlobalTrafficPoliciesGetter has a method to return a GlobalTrafficPolicyInterface.
// A group's client should implement this interface.
type GlobalTrafficPoliciesGetter interface {
	GlobalTrafficPolicies(namespace string) GlobalTrafficPolicyInterface
}

// GlobalTrafficPolicyInterface has methods to work with GlobalTrafficPolicy resources.
type GlobalTrafficPolicyInterface interface {
	Create(*v1.GlobalTrafficPolicy) (*v1.GlobalTrafficPolicy, error)
	Update(*v1.GlobalTrafficPolicy) (*v1.GlobalTrafficPolicy, error)
	UpdateStatus(*v1.GlobalTrafficPolicy) (*v1.GlobalTrafficPolicy, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.GlobalTrafficPolicy, error)
	List(opts metav1.ListOptions) (*v1.GlobalTrafficPolicyList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.GlobalTrafficPolicy, err error)
	GlobalTrafficPolicyExpansion
}

// globalTrafficPolicies implements GlobalTrafficPolicyInterface
type globalTrafficPolicies struct {
	client rest.Interface
	ns     string
}

// newGlobalTrafficPolicies returns a GlobalTrafficPolicies
func newGlobalTrafficPolicies(c *AdmiralV1Client, namespace string) *globalTrafficPolicies {
	return &globalTrafficPolicies{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the globalTrafficPolicy, and returns the corresponding globalTrafficPolicy object, and an error if there is any.
func (c *globalTrafficPolicies) Get(name string, options metav1.GetOptions) (result *v1.GlobalTrafficPolicy, err error) {
	result = &v1.GlobalTrafficPolicy{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("globaltrafficpolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of GlobalTrafficPolicies that match those selectors.
func (c *globalTrafficPolicies) List(opts metav1.ListOptions) (result *v1.GlobalTrafficPolicyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.GlobalTrafficPolicyList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("globaltrafficpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested globalTrafficPolicies.
func (c *globalTrafficPolicies) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("globaltrafficpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a globalTrafficPolicy and creates it.  Returns the server's representation of the globalTrafficPolicy, and an error, if there is any.
func (c *globalTrafficPolicies) Create(globalTrafficPolicy *v1.GlobalTrafficPolicy) (result *v1.GlobalTrafficPolicy, err error) {
	result = &v1.GlobalTrafficPolicy{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("globaltrafficpolicies").
		Body(globalTrafficPolicy).
		Do().
		Into(result)
	return
}

// Update takes the representation of a globalTrafficPolicy and updates it. Returns the server's representation of the globalTrafficPolicy, and an error, if there is any.
func (c *globalTrafficPolicies) Update(globalTrafficPolicy *v1.GlobalTrafficPolicy) (result *v1.GlobalTrafficPolicy, err error) {
	result = &v1.GlobalTrafficPolicy{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("globaltrafficpolicies").
		Name(globalTrafficPolicy.Name).
		Body(globalTrafficPolicy).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *globalTrafficPolicies) UpdateStatus(globalTrafficPolicy *v1.GlobalTrafficPolicy) (result *v1.GlobalTrafficPolicy, err error) {
	result = &v1.GlobalTrafficPolicy{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("globaltrafficpolicies").
		Name(globalTrafficPolicy.Name).
		SubResource("status").
		Body(globalTrafficPolicy).
		Do().
		Into(result)
	return
}

// Delete takes name of the globalTrafficPolicy and deletes it. Returns an error if one occurs.
func (c *globalTrafficPolicies) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("globaltrafficpolicies").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *globalTrafficPolicies) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("globaltrafficpolicies").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched globalTrafficPolicy.
func (c *globalTrafficPolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.GlobalTrafficPolicy, err error) {
	result = &v1.GlobalTrafficPolicy{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("globaltrafficpolicies").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
